name: dev-firenet
services:
  firenet-dev-app:
    build: .
    container_name: firenet-dev-app
    hostname: firenet-dev-app
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    restart: always
    environment:
      FLASK_ENV: production
      DB_HOST: firenet-dev-db
      DB_NAME: firenet
      DB_USER: root
      DB_PASSWORD: '123@Mudar'
    depends_on:
      - firenet-dev-db

  firenet-dev-db:
    image: mysql:latest
    container_name: firenet-dev-db
    hostname: firenet-dev-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123@Mudar'
      MYSQL_DATABASE: firenet
    volumes:
      - /srv/firenet-dev-db:/var/lib/mysql

  firenet-phpmyadmin:
    image: phpmyadmin:latest
    container_name: firenet-phpmyadmin
    hostname: firenet-phpmyadmin
    restart: always
    environment:
      PMA_HOSTS: 'firenet-dev-db'
    ports:
      - "8081:80"
